### PR TITLE
Pass key into multifeed via kappa-core for multifeed encryption

### PR DESCRIPTION
**Pull request by nikolaiwarner**
and update packages

### CODE REVIEW

**Comment by noffle** [comment]
Nice. You tested that it works?

**Comment by nikolaiwarner** [comment]
@noffle 

Running this with an existing key gives me this error:
`Error: Another hypercore is stored here` from node_modules/hypercore/index.js:258:17

Running it with a new key starts up like normal but closing and starting again results in the above error.

**Comment by noffle** [comment]
I bet a pretty penny that it's because multifeed passes its `this._opts` into the hypercores it creates, so the `opts.key` ends up being interpreted as the key to use every hypercore! See here: https://github.com/kappa-db/multifeed/blob/master/index.js#L108

I think this could be fixed by renaming the `opts.key` in multifeed to something clearer like `opts.encryptionKey` or `opts.commonKey`. That, or removing `opts.key` from the object passed into hypercore creation.

**Comment by karissa** [comment]
yeah, also we could probably do a lot to improve type checking options as they're passed down through objects across the ecosystem

**Comment by noffle** [comment]
I forgot about this PR and recently re-implemented this!

**Pull request closed without merging**
