### PR TITLE
Replace discovery-swarm with hyperswarm

### PR DESCRIPTION
**Pull request by noffle**
Based on @nikolaiwarner's original work in #32.

This removes discovery-swarm for finding peers. Peers before this change will not be able to discovery peers from this commit onwards.

### CODE REVIEW

**Comment by noffle** [comment]
I'm going to do this as a prerelease version on npm, so folx can opt-in and we can see how reliable it feels.

**Comment by noffle** [comment]
Travis failure was due to a timeout re: swarm shutdown in the tests.

**Comment by cblgh** [comment]
🎉 ⭐️

**Comment by todrobbins** [comment]
Yay! 🌸

**Comment by okdistribute** [comment]
nice!

**Comment by noffle** [comment]
- [x] `cabal-core@10.0.0` published
- [x] `cabal-client@3.0.0-prerelease` published
- [x] cli client: `cabal@prerelease` published
- [ ] desktop client: `cabal-desktop@???` published  (cc @nickwarner, if you have the spoons <3)

**Comment by nikolaiwarner** [comment]
👍 👍 👍🥣  @noffle cabal desktop 5.0.0-prerelease is ready -> https://github.com/cabal-club/cabal-desktop/releases/tag/v5.0.0-prerelease ❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️

**Comment by noffle** [comment]
@nikolaiwarner heck ya! (and sorry for misspelling your username!)

**Pull request merged**
